In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/home/navjot/.local/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9722222222222222

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [11]:
rf = RandomForestClassifier(n_estimators=130)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

If we use train-test-split, it divides the data randomly so model can give different result everytime.

In [13]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [14]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [15]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [16]:
#StratifiedKFold-When you are seperating out the folds, it will divide each classification category in uniform way
from sklearn.model_selection import StratifiedKFold
SkFold = StratifiedKFold(n_splits=3)

In [30]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver = 'liblinear'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [31]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [32]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [33]:
scores_rf

[0.9365609348914858, 0.9532554257095158, 0.9215358931552587]

**cross_val_score:** this will do the exact same thing as it was done in above steps, ie, splitting data in folds, fitting the model and returning the score on test data.

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [36]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.94166667, 0.91944444, 0.94986072, 0.95543175, 0.93036212])